<?php
//Maha ganapathaye Namah!
//Bookstore FrontEnd V 1.0
//� I biz Info Solutions
require_once (__DIR__.'/includes/classes/global.inc.php');
include(__DIR__.'/includes/header.php');
?>
<!-- Support starts -->

      <div class="support container">
         <div class="row">
          <div class="col-md-12">
            <div class="support-page well">
                 <!-- Lists -->
                 <ul id="slist">
                     <li>This document is an electronic record in terms of Information Technology Act, 2000 and rules there under &nbsp;as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</li>
                     <li>Your use of a Prabhus Books website www.prabhusbooks.com (hereinafter referred to as &quot;Prabhus Books&quot;) and services and tools are governed by the following terms and conditions as applicable to the Prabhus Books. If you transact on Prabhus Books, you shall be subject to the policies that are applicable to the website for such transaction. By mere use of the website you shall be contracting with M/s Prabhus Books,&nbsp; a firm incorporated under Partnership Act, 1932 with registered office at Ayurveda College Jn, Old Sreekandeswaram Road, Thiruvananthapuram, Kerala - 695 001, India and these terms and conditions constitute your binding obligations.</li>
                     <li>
		For the purpose of these terms of use, wherever the context so require &lsquo;You&rsquo; shall mean any natural or legal person who has agreed to become a member of the Website by providing Registration Data &nbsp;while registering on the Website as Registered User using the computer systems of the Prabhus Books.</li>
    <li>
		When you use any of the services provided by the Prabhus Books, including but not limited to, (e.g., Customer Reviews), you will be subject to the rules, guidelines, policies, terms, and conditions applicable to such service, and they shall be deemed to be incorporated into this Terms of Use and shall be considered as part and parcel of this Terms of Use. Prabhus Books reserves the right, at its sole discretion, to change, modify, add or remove portions of these Terms of Use, at any time. It is your responsibility to check these Terms of Use periodically for changes. Your continued use of the Site following the posting of changes will mean that you accept and agree to the changes. As long as you comply with these Terms of Use, Prabhus Books grants you a personal, non-exclusive, non-transferable, limited privilege to enter and use the Site.</li>
	<li>
		<strong>ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS IN THIS AGREEMENT, SO PLEASE READ THIS AGREEMENT CAREFULLY BEFORE PROCEEDING</strong></li>
    <h6>
		Membership Eligibility</h6>
    <li>
		Use of the Prabhus Books Website is available only to persons who can form legally binding contracts under Indian Contract Act, 1872. Persons who are &quot;incompetent to contract&quot; within the meaning of the Indian Contract Act, 1872 including minors, un-discharged insolvents etc. are not eligible to use the Prabhus Books Website. If you are a minor i.e. under the age of 18 years, you shall not register as a member of the Prabhus Books and shall not transact or use Prabhus Books website. As a minor if you wish to use or transact on Prabhus Books, such use or transaction may be made by your legal guardian or parents who have registered as users of the Prabhus Books. Prabhus Books reserves the right to terminate your membership and refuse to provide you with access to the Prabhus Books if it is brought to Prabhus Books&rsquo;s notice or if it is discovered that you are under the age of 18 years.</li>
	<h6>
		Your Account and Registration Obligations</h6>
	<li>
		If you use Prabhus Books, you shall be responsible for maintaining the confidentiality of your User ID and Password and you shall be responsible for all activities that occur under your User ID and Password. You agree that if you provide any information that is untrue, inaccurate, not current or incomplete or Prabhus Books has reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or not in accordance with the this Terms of Use, Prabhus Books has the right to indefinitely suspend or terminate or block access of your membership with Prabhus Books and refuse to provide you with access to the Website.</li>
	<h6>
		Communications</h6>
	<li>
		When You use the Website or send emails or other data, information or communication to Prabhus Books, You agree and understand that You are communicating with Prabhus Books through electronic records and You consent to receive communications via electronic records from Prabhus Books periodically and as and when required. Prabhus Books may communicate with You by email or by such other mode of communication, electronic or otherwise.</li>
	<h6>
		Charges</h6>
	<li>
		Membership on the Prabhus Books is free. Prabhus Books does not charge any fee for browsing and buying on the Prabhus Books. However Prabhus Books reserves the right to charge fee and change its policies from time to time. In particular, Prabhus Books may at its sole discretion introduce new services and modify some or all of the existing services offered on the Prabhus Books. In such an event Prabhus Books reserves, without notice to You, the right to introduce fees for the new services offered or amend/introduce fees for existing services, as the case may be. Changes to the Fee and related policies shall automatically become effective immediately once implemented on Prabhus Books. Unless otherwise stated, all fees shall be quoted in Indian Rupees. You shall be solely responsible for compliance of all applicable laws including those in India for making payments to Prabhus Books.</li>
	<h6>
		Use of Prabhus Books Website www.prabhusbooks.com</h6>
	<li>
		You agree, undertake and confirm that your use of Prabhus Books shall be strictly governed by the following binding principles:</li>
	<h6>
		1. &nbsp;You shall not host, display, upload, modify, publish, transmit, update or share any information:</h6>
	<li>
		<br />
		(a) belongs to another person and to which You does not have any right to.<br />
		(b) is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic, libellous, invasive of another&#39;s privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever; or unlawfully threatening or unlawfully harassing including but not limited to &quot;indecent representation of women&quot; within the meaning of the Indecent Representation of Women (Prohibition) Act, 1986;<br />
		(c) misleading in any way.&nbsp;<br />
		(d) is patently offensive to the online community, such as sexually explicit content, or content that promotes obscenity, pedophilia, racism, bigotry, hatred or physical harm of any kind against any group or individual;&nbsp;<br />
		(e) harasses or advocates harassment of another person;<br />
		(f) involves the transmission of &quot;junk mail,&quot; &quot;chain letters,&quot; or unsolicited mass mailing or &quot;spamming&quot;;&nbsp;<br />
		(g) promotes illegal activities or conduct that is abusive, threatening, obscene, defamatory or libelous;<br />
		(h) infringes upon or violates any third party&#39;s rights [(including, but not limited to, intellectual property rights, rights of privacy (including without limitation unauthorized disclosure of a person&#39;s name, email address, physical address or phone number) or rights of publicity];<br />
		(i) promotes an illegal or unauthorized copy of another person&#39;s copyrighted work (see &quot;Copyright complaint&quot; below for instructions on how to lodge a complaint about uploaded copyrighted material), such as providing pirated computer programs or links to them, providing information to circumvent manufacture-installed copy-protect devices, or providing pirated music or links to pirated music files;<br />
		(j) contains restricted or password-only access pages, or hidden pages or images (those not linked to or from another accessible page);<br />
		(l) provides material that exploits people in a sexual, violent or otherwise inappropriate manner or solicits personal information from anyone;<br />
		(m) provides instructional information about illegal activities such as making or buying illegal weapons, violating someone&#39;s privacy, or providing or creating computer viruses;<br />
		(n) contains video, photographs, or images of another person age 18 or older without his or her express written consent and permission or those of any minor (regardless of whether you have consent from the minor or his or her legal guardian).<br />
		(o) tries to gain unauthorized access or exceeds the scope of authorized access (as defined herein and in other applicable Codes of Conduct or End User Access and License Agreements) to the Sites or to profiles, blogs, communities, account information, bulletins, friend request, or other areas of the Sites or solicits passwords or personal identifying information for commercial or unlawful purposes from other users;<br />
		(p) engages in commercial activities and/or sales without Prabhus Books&#39;s prior written consent such as contests, sweepstakes, barter, advertising and pyramid schemes, or the buying or selling of &quot;virtual&quot; items related to the Sites. Throughout this Terms of Use, Prabhus Books &quot;prior written consent&quot; means a communication coming from Prabhus Books Legal department, specifically in response to your request, and specifically addressing the activity or conduct for which you seek authorization;<br />
		(q) solicits gambling or engages in any gambling activity which Prabhus Books, in its sole discretion, believes is or could be construed as being illegal;<br />
		(r) interferes with another user&#39;s use and enjoyment of the Prabhus Books Website or any other individual&#39;s user and enjoyment of similar services;<br />
		(s) refers to any website or URL that, in the sole discretion of Prabhus Books, contains material that is inappropriate for the Prabhus Books Website or any other Website, contains content that would be prohibited or violates the letter or spirit of these Terms of Use.<br />
		(t) harm minors in any way;<br />
		(u) infringes any patent, trademark, copyright or other proprietary rights or &nbsp;third party&rsquo;s trade secrets or rights of publicity or privacy or shall not be fraudulent or involve the sale of counterfeit or stolen items;&nbsp;<br />
		(v) violates any law for the time being in force;<br />
		(w) deceives or misleads the addressee/ users about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;<br />
		(x) impersonate another person;<br />
		(y) contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource; or contains any Trojan horses, worms, time bombs, cancelbots, easter eggs or other computer programming routines that may damage, detrimentally interfere with, diminish value of, surreptitiously intercept or expropriate any system, data or personal information;&nbsp;<br />
		(z) threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting any other nation.<br />
		(aa) shall not be false, inaccurate or misleading;&nbsp;<br />
		(ab) shall not, directly or indirectly, offer, attempt to offer, trade or attempt to trade in any item, the dealing of which is prohibited or restricted in any manner under the provisions of any applicable law, rule, regulation or guideline for the time being in force.&nbsp;<br />
		(ac) shall not create liability for us or cause us to lose (in whole or in part) the services of our ISPs or other suppliers;</li>
	<li>
		2. &nbsp;You shall not use any &ldquo;deep-link&rdquo;, &ldquo;page-scrape&rdquo;, &ldquo;robot&rdquo;, &ldquo;spider&rdquo; or other automatic device, program, algorithm or methodology, or any similar or equivalent manual process, to access, acquire, copy or monitor any portion of the Website or any Content, or in any way reproduce or circumvent the navigational structure or presentation of the Website or any Content, to obtain or attempt to obtain any materials, documents or information through any means not purposely made available through the Website. Prabhus Books reserves the right to bar any such activity.</li>
	<li>
		3. &nbsp; &nbsp;You shall not attempt to gain unauthorized access to any portion or feature of Prabhus Books website, or any other systems or networks connected to Prabhus Books Website or to any Prabhus Books&rsquo;s server, computer, network, or to any of the services offered on or through Prabhus Books Website, by hacking, password &ldquo;mining&rdquo; or any other illegitimate means.</li>
	<li>
		4. &nbsp;You shall not probe, scan or test the vulnerability of Prabhus Books website or any network connected to Prabhus Books website nor breach the security or authentication measures on Prabhus Books website or any network connected to Prabhus Books Website. You may not reverse look-up, trace or seek to trace any information on any other user of or visitor to Prabhus Books Website, or any other customer of Prabhus Books, including any Prabhus Books account not owned by you, to its source, or exploit Prabhus Books Website or any service or information made available or offered by or through Prabhus Books Website, in any way where the purpose is to reveal any information, including but not limited to personal identification or information, other than your own information, as provided for by Prabhus Books Website.</li>
	<li>
		5. &nbsp;You agree that you will not take any action that imposes an unreasonable or disproportionately large load on the infrastructure of Prabhus Books Website or Prabhus Books&rsquo;s systems or networks, or any systems or networks connected to the Prabhus Books.</li>
	<li>
		6. You agree not to use any device, software or routine to interfere or attempt to interfere with the proper working of the Website or any transaction being conducted on the Website, or with any other person&rsquo;s use of the Website.</li>
	<li>
		7. You may not forge headers or otherwise manipulate identifiers in order to disguise the origin of any message or transmittal you send to Prabhus Books on or through the Website or any service offered on or through the Website. You may not pretend that you are, or that you represent, someone else, or impersonate any other individual or entity.</li>
	<li>
		8. You may not use the Website or any Content for any purpose that is unlawful or prohibited by these Terms of Use, or to solicit the performance of any illegal activity or other activity which infringes the rights of Prabhus Books or others.</li>
	<li>
		9. Solely to enable Prabhus Books to use the information you supply us with, so that we are not violating any rights you might have in Your Information, you agree to grant us a non-exclusive, worldwide, perpetual, irrevocable, royalty-free, sub-licensable (through multiple tiers) right to exercise the copyright, publicity, database rights or any other rights you have in Your Information, in any media now known or not currently known, with respect to Your Information. Prabhus Books will only use Your Information in accordance with the terms of use and Prabhus Books&rsquo;s Privacy Policy.</li>
	<li>
		10. From time to time, you shall be responsible for providing information relating to the items or services proposed to be sold by you. In this connection, you undertake that all such information shall be accurate in all respects. You shall not exaggerate or over emphasize the attributes of such items or services so as to mislead other Users in any manner.</li>
	<li>
		11. You shall not engage in advertising to, or solicitation of, other users of Prabhus Books to buy or sell any products or services, including, but not limited to, products or services related being displayed on Prabhus Books or related to Prabhus Books. You may not transmit any chain letters or unsolicited commercial or junk email to other users via Prabhus Books. It shall be a violation of these Terms of Use to use any information obtained from Prabhus Books in order to harass, abuse, or harm another person, or in order to contact, advertise to, solicit, or sell to another person outside of the Prabhus Books without Prabhus Books&rsquo;s prior explicit consent. In order to protect our users from such advertising or solicitation, Prabhus Books reserves the right to restrict the number of messages or emails which a user may send to other users in any 24-hour period which Prabhus Books deems appropriate in its sole discretion.12. You understand that Prabhus Books has the right at all times to disclose any information (including the identity of the persons providing information or materials on the Prabhus Books Website) as necessary to satisfy any law, regulation or valid governmental request. This may include, without limitation, disclosure of the information in connection with investigation of alleged illegal activity or solicitation of illegal activity or in response to a lawful court order or subpoena. In addition, we can (and you hereby expressly authorize us to) disclose any information about you to law enforcement or other government officials, as we, in our sole discretion, believe necessary or appropriate in connection with the investigation and/or resolution of possible crimes, especially those that may involve personal injury.</li>
	<li>
		12. &nbsp;Prabhus Books reserves the right, but has no obligation, to monitor the materials posted on Prabhus Books website. Prabhus Books shall have the right to remove or edit any Content that in its sole discretion violates, or is alleged to violate, any applicable law or either the spirit or letter of these Terms of Use. Notwithstanding this right of Prabhus Books, YOU REMAIN SOLELY RESPONSIBLE FOR THE CONTENT OF THE MATERIALS YOU POST ON THE PRABHUS BOOKS WEBSITE AND IN YOUR PRIVATE MESSAGES. Please be advised that such Content posted does not necessarily reflect the views of Prabhus Books. In no event shall Prabhus Books assume or have any responsibility or liability for any Content posted or for any claims, damages or losses resulting from use of Content and/or appearance of Content on Prabhus Books. You hereby represent and warrant that you have all necessary rights in and to all Content you provide and all information it contains and that such Content shall not infringe any proprietary or other rights of third parties or contain any libelous, tortious, or otherwise unlawful information.</li>
	<li>
		13. Your correspondence or business dealings with, or participation in promotions of, advertisers found on or through Prabhus Books, including payment and delivery of related goods or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between you and such advertiser. Prabhus Books shall not be responsible or liable for any loss or damage of any sort incurred as the result of any such dealings or as the result of the presence of such advertisers on Prabhus Books.</li>
	<li>
		14. It is possible that other users (including unauthorized users or &ldquo;hackers&rdquo;) may post or transmit offensive or obscene materials on Prabhus Books and that you may be involuntarily exposed to such offensive and obscene materials. It also is possible for others to obtain personal information about you due to your use of Prabhus Books, and that the recipient may use such information to harass or injure you. Prabhus Books does not approve of such unauthorized uses but by using the Prabhus Books Website you acknowledge and agree that Prabhus Books is not responsible for the use of any personal information that you publicly disclose or share with others on Prabhus Books. Please carefully select the type of information that you publicly disclose or share with others on Prabhus Books.</li>
	<li>
		15. &nbsp; Prabhusbooks.com shall have all the rights to take necessary action and claim damages that may occur due to your involvement/participation in any way on your own or through group/s of People, intentionally or unintentionally in DoS/DDoS (Distributed Denial of Services).</li>
	<h6>
		Contents Posted on Site</h6>
	<li>
		All text, graphics, user interfaces, visual interfaces, photographs, trademarks, logos, sounds, music, artwork and computer code (collectively, &ldquo;Content&rdquo;), including but not limited to the design, structure, selection, coordination, expression, &ldquo;look and feel&rdquo; and arrangement of such Content, contained on the Prabhus Books is owned, controlled or licensed by or to Prabhus Books, and is protected by trade dress, copyright, patent and trademark laws, and various other intellectual property rights and unfair competition laws.</li>
	<li>
		Except as expressly provided in these Terms of Use, no part of the Prabhus Books and no Content may be copied, reproduced, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted or distributed in any way (including &ldquo;mirroring&rdquo;) to any other computer, server, website or other medium for publication or distribution or for any commercial enterprise, without Prabhus Books&rsquo;s express prior written consent.</li>
	<li>
		You may use information on Prabhus Books products and services purposely made available by Prabhus Books for downloading from the Site, provided that you (1) not remove any proprietary notice language in all copies of such documents, (2) use such information only for your personal, non-commercial informational purpose and do not copy or post such information on any networked computer or broadcast it in any media, (3) make no modifications to any such information, and (4) not make any additional representations or warranties relating to such documents.</li>
	<li>
		You shall be responsible for any notes, messages, e-mails, billboard postings, photos, drawings, profiles, opinions, ideas, images, videos, audio files or other materials or information posted or transmitted to the Sites (collectively, &quot;Content&quot;). Such Content will become the property of Prabhus Books and you grant Prabhus Books the worldwide, perpetual and transferable rights in such Content. Prabhus Books shall be entitled to, consistent with our Privacy Policy, use the Content or any of its elements for any type of use forever, including but not limited to promotional and advertising purposes and in any media whether now known or hereafter devised, including the creation of derivative works that may include Content you provide. You agree that any Content you post may be used by Prabhusbooks.com, consistent with our Privacy Policy and Rules of Conduct on Site as mentioned herein, and you are not entitled to any payment or other compensation for such use.</li>
	<h6>
		Other Businesses</h6>
	<li>
		Prabhus Books does not take responsibility or liability for the actions, products, content and services on Prabhus Books website, which are linked to Affiliates and / or third party websites using Prabhus Books APIs or otherwise. In addition, Prabhus Books may provide links to the third party websites of affiliated companies and certain other businesses for which, Prabhus Books assumes no responsibility for examining or evaluating the products and services offered by them, and Prabhus Books does not warrant the offerings of, any of these businesses or individuals or the content of such third party website(s). Prabhus Books does not in any way endorse any third party website(s) or content thereof</li>
	<h6>
		Links</h6>
	<li>
		Prabhus Books welcomes links to this site. You may establish a hypertext link to Prabhus Books website, provided that the link does not state or imply any sponsorship or endorsement of your site by Prabhus Books. You must not use on your site or in any other manner any trademarks, service marks or any other materials appearing on the Prabhus Books, including any logos or characters, without the express written consent of Prabhus Books and the owner of the mark or materials. You must not frame or otherwise incorporate into another third party website or present in conjunction with or juxtaposed against such a website any of the content or other materials on the Prabhus Books website without Prabhus Books&rsquo;s prior written consent.</li>
	<h6>
		Privacy</h6>
	<li>
		We view protection of Your privacy as a very important principle. We understand clearly that you and Your Personal Information is one of our most important assets. We store and process Your Information on computers that may be protected by physical as well as reasonable technological security measures and procedures in accordance with Information Technology Act 2000 and rules there under. Our current Privacy Policy is available at http://www.Prabhusbooks.com/privacypolicy.php. If you object to your Information being transferred or used in this way please do not use Prabhus Books Website</li>
	<h6>
		MANDATORY DECLARATION &ndash; COMPUTERS</h6>
	<li>
		1. &nbsp;You hereby declare that you have provided all necessary Legal Details for the shipment of the product to the destination specified by you in the Order.</li>
	<li>
		2. &nbsp;You further declare that the Product will be acquired for personal use of the Consignee and/or Buyer. The Product will not be sold, resold, bartered or in any way disposed for profit.</li>
	<h3>
		Disclaimer Of Warranties And Liability</h3>
	<li>
		This website, all the materials and products (including but not limited to software) and services, included on or otherwise made available to you through this site are provided on Prabhus Books on &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis without any representation or warranties, express or implied except otherwise specified in writing. Without prejudice to the forgoing paragraph, Prabhus Books does not warrant that:</li>
	<li>
		This website will be constantly available, or available at all; or</li>
	<li>
		The information on this website is complete, true, accurate or non-misleading.</li>
	<li>
		Prabhus Books will not be liable to you in any way or in relation to the contents of, or use of, or otherwise in connection with, Prabhus Books website.</li>
	<li>
		Prabhus Books does not warrant that this site; information, content, materials, product (including software) or services included on or otherwise made available to you through Prabhus Books website; their servers; or electronic communication sent from Prabhus Books are free of viruses or other harmful components.</li>
	<li>
		Nothing on Prabhus Books constitutes, or is meant to constitute, advice of any kind.</li>
	<li>
		All the products sold on Prabhus Books are governed by different state laws and if Prabhus Books is unable to deliver such products due to implications of different state laws, Prabhus Books will return or will give credit for the amount received by Prabhus Books from the sale of such product, that could not be delivered to you.</li>
	<li>
		You will be required to enter a valid phone number while placing an order on Prabhus Books. By registering your phone number with us, you consent to be contacted by Prabhus Books via phone calls and / or SMS notifications, in case of any order or shipment or delivery related updates. Prabhus Books will not use your personal information to initiate any promotional phone calls or SMS&#39;.</li>
	<h3>
		Services</h3>
	<li>
		&nbsp;</li>
	<li>
		<strong>Payment</strong></li>
	<li>
		While availing any of the payment method/s offered at Prabhus Books, Prabhus Books will not be responsible or assume any liability, whatsoever in respect of any loss or damage arising directly or indirectly to you due to:</li>
	<li>
		&nbsp;</li>
	<li>
		1.Lack of authorization for any transaction/s, or</li>
	<li>
		2. Exceeding the preset limit mutually agreed by you and between your &quot;Bank/s&quot;, or</li>
	<li>
		3. &nbsp;Any payment issues arising out of the transaction, or</li>
	<li>
		4. &nbsp;Decline of transaction for any other reason/s.</li>
	<li>
		All payments made against the purchases/services on Prabhus Books by you shall be compulsorily in Indian Rupees acceptable by the Union of India. Prabhus Books does not accept any other form of currency with respect to the purchases made on Prabhus Books.</li>
	<h6>
		Payment</h6>
	<li>
		While availing any of the payment method/s offered by us, we are not responsible or take no liability of whatsoever nature in respect of any loss or damage arising directly or indirectly to you out of the decline due to:<br />
		1. lack of authorization for any transaction/s,&nbsp;<br />
		2. or exceeding the preset limit mutually agreed by you and between your &quot;Bank/s&quot;,&nbsp;<br />
		3. or any payment issues arising out of the transaction,<br />
		4. or decline of transaction for any other reason/s.</li>
	<li>
		&nbsp;</li>
	<li>
		All payments made against the purchases/services on Prabhusbooks.com by you shall be compulsorily in Indian Rupees acceptable by the Union of India. Prabhusbooks.com does not accept any other form of currency with respect to the purchases.</li>
	<h6>
		Breach</h6>
	<li>
		Without limiting other remedies, Prabhus Books may limit your activity, immediately remove your information, warn other Users of your actions, immediately temporarily/indefinitely suspend or terminate or block your membership, and/or refuse to provide you with access to the Prabhus Books website in the event, but not limited to:</li>
	<li>
		&nbsp;</li>
	<li>
		1. If you breach the Terms of Use or Privacy Policy or other rules and &nbsp;policies, if any;</li>
	<li>
		2. If Prabhus Books is unable to verify or authenticate any information you provide; or</li>
	<li>
		3. If it is believed that your actions may cause legal liability for you, other Users or Prabhus Books. Prabhus Books may at any time at its sole discretion reinstate suspended Users. A User that has been suspended or blocked may not register or attempt to register with Prabhus Books or use Prabhus Books Website in any manner whatsoever until such time that such User is reinstated by Prabhus Books. Notwithstanding the foregoing, if you breach the Terms of Use or Privacy Policy or other ruler and policies, Prabhus Books reserves the right to recover any amounts due and owing by you to Prabhus Books and to take strict legal action including but not limited to a referral to the appropriate police or other authorities for initiating criminal or other proceedings against you</li>
	<h3>
		Indemnity</h3>
	<li>
		You shall indemnify and hold harmless Prabhus Books its owner, licensee, affiliates, subsidiaries, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorneys&#39; fees, made by any third party or penalty imposed due to or arising out of your breach of this Terms of Use, privacy Policy and other Policies, or your violation of any law, rules or regulations or the rights of a third party.</li>
	<h6>
		Applicable Law</h6>
	<li>
		This Agreement shall be governed by and interpreted and construed in accordance with the laws of India. The place of jurisdiction shall be exclusively in Thiruvananthapuram.</li>
	<h6>
		Jurisdictional Issues/Sale in India Only</h6>
	<li>
		Unless otherwise specified, the material on Prabhus Books is presented solely for the purpose of sale in India. Prabhus Books makes no representation that materials in Prabhus Books are appropriate or available for use in other locations/Countries other than India. Those who choose to access this site from other locations/Countries other than India do so on their own initiative and Prabhus Books is not responsible for supply of goods/refund for the goods ordered from other locations/Countries other than India, compliance with local laws, if and to the extent local laws are applicable.</li>
	<h6>
		Trademark, Copyright and Restriction</h6>
	<li>
		This site is controlled and operated by Prabhus Books. All material on this site, including images, illustrations, audio clips, and video clips, are protected by copyrights, trademarks, and other intellectual property rights that are owned and controlled by us or by other parties that have licensed their material to us. Material on Prabhus Books web site owned, operated, licensed or controlled by us is solely for your personal, non-commercial use. You must not copy, reproduce, republish, upload, post, transmit or distribute such material in any way, including by e-mail or other electronic means and whether directly or indirectly and you must not assist any other person to do so. Without the prior written consent of the owner, modification of the materials, use of the materials on any other web site or networked computer environment or use of the materials for any purpose other than personal, non-commercial use is a violation of the copyrights, trademarks and other proprietary rights, and is prohibited. Any use for which you receive any remuneration, whether in money or otherwise, is a commercial use for the purposes of this clause.</li>
	<h6>
		<br />
		Copyright complaint</h6>
	<li>
		We at Prabhus Books respect the intellectual property of others. In case you feel that your work has been copied in a way that constitutes copyright infringement you can write to us at admin(at)prabhusbooks(dot)com.</li>
	<h6>
		Risk of loss</h6>
	<li>
		All items purchased from Prabhusbooks.com are made pursuant to a shipment contract. This means that the risk of loss and title for such items pass to you upon our delivery to the carrier.</li>
	<h6>
		Product Description</h6>
	<li>
		Prabhusbooks.com tries to be as accurate as possible. However, Prabhusbooks.com does not warrant that product description or other content of this site is accurate, complete, reliable, current, or error-free</li>
	<h6>
		<br />
		Pricing/Typographical error</h6>
	<li>
		If Prabhusbooks.com comes across any difference in pricing resulting from typographic errors wrt pricing or product information, Prabhusbooks.com shall have the right to rectify the same or cancel the order(s) and refund monies, if any, collected from the customer within 10-15 business days of such corrective action taken.&nbsp;The mode of refund will be the same as at the time of placing the order. Cash on Delivery order refunds will be done by cheque.</li>
	<h6>
		&nbsp;Replacement</h6>
	<li>
		Prabhusbooks.com Doesn&rsquo;t offers you REPLACEMENT product/s ordered on Prabhusbooks.com any how if at the time of delivery and/or within 30 days from the date of delivery of the product/s, if any Manufacturing defect is found, then the buyer of the product/s can ask for replacement of the product/s subject to the following terms and conditions:</li>
	<li>
		1 &nbsp; &nbsp;Notify us of any defects in the product/s at the time of delivery of the product/s and/or within 5 days from the date of delivery and the same product/s will be replaced in return of the defective product/s.</li>
	<li>
		2&nbsp;&nbsp;&nbsp; Replacement can be for the entire product/s or part/s of the product subject to availability of the same with&nbsp;Prabhusbooks.com.</li>
	<li>
		3&nbsp;&nbsp;&nbsp; Replacement is offered for the product/s sold by&nbsp;<a href="http://www.prabhusbooks.com" target="_blank">Prabhusbooks.com</a>&nbsp;ONLY.</li>
	<li>
		&nbsp;</li>
	<li>
		<strong>Following products shall not be eligible for return or replacement:</strong></li>
	<li>
		&bull; Damages due to misuse of product;</li>
	<li>
		&bull; Incidental damage due to malfunctioning of product;</li>
	<li>
		&bull; Products with tampered or missing serial/UPC numbers;</li>
	<li>
		&bull; Any damage/defect which are not covered under the manufacturer&#39;s warranty</li>
	<li>
		&bull; Any product that is returned without all original packaging and accessories, including the box, manufacturer&#39;s packaging if any, and all other items originally included with the product/s delivered;</li>
	<li>
		&nbsp;</li>
	<li>
		Disclaimer: &quot;ANY DECISION ON 30 DAY REPLACEMENT GUARANTEE ON THE PRODUCT/S SOLD BY Prabhusbooks.com is at the sole discretion of Seller&nbsp;and decision of Seller&nbsp;shall be final and binding. Seller reserves the right to withdraw and/or alter from 30 DAY REPLACEMENT GUARANTEE at any time without giving any intimation of whatsoever nature.&quot;</li>
	<li>
		<strong>Availability</strong></li>
	<li>
		Once order placed in prabhusbooks.com, you cannot cancel the order. Available products/Services will be supplied within 1-3 business days and non-available products/Services will be back ordered and supplied</li>
	<h6>
		Cancellation of order</h6>
	<li>
		Prabhusbooks.com reserves the right to cancel any order without any explanation for doing so, under situation where Prabhusbooks.com is not able to meet the requirement of the order placed or order so placed/cancelled does not comply with the Prabhusbooks.com policy or for any other reason. However, Prabhusbooks.com will ensure that any communication of cancellation of an order, so cancelled, is intimated within appropriate time to the concerned person and any applicable refund, will be made in reasonable time.</li>
	<h6>
		Limitation of Liability</h6>
	<li>
		IN NO EVENT SHALL PRABHUSBOOKS.COM BE LIABLE FOR ANY SPECIAL, INCIDENTAL, INDIRECT OR CONSEQUENTIAL DAMAGES OF ANY KIND IN CONNECTION WITH THIS AGREEMENT, EVEN IF PRABHUSBOOKS.COM HAS BEEN INFORMED IN ADVANCE OF THE POSSIBILITY OF SUCH DAMAGES.</li>
	<h6>
		Our Contact</h6>
	<li>
		Please send any questions or comments (including all inquiries unrelated to copyright infringement) regarding this Site to&nbsp;admin(at)prabhusbooks(dot)com</li>
                </ul>
            </div>
         </div>
         </div>
         </div>
